const c = {
  CHANGE_ACTIVE_CATEGORY: 'CHANGE_ACTIVE_CATEGORY',
  GET_POSTS: 'GET_POSTS',
  CREATE_POST: 'CREATE_POST',
  DELETE_POST: 'DELETE_POST',
  CHANGE_PAGE: 'CHANGE_PAGE'
};

export default c;
